eenable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
riplib = true

patches-source = "Morpheapp/morphe-patches"
cli-source = "AzyrRuthless/morphe-cli"
rv-brand = "Morphe"
patches-version = "dev"
cli-version = "latest"

#Morphe
[YouTube]
build-mode = "module"
excluded-patches = "'Swipe controls' 'Custom branding' 'Change form factor' 'Shorts autoplay' 'Alternative thumbnails' 'Bypass image region restrictions' 'Enable debugging'"
version = "auto"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
build-mode = "module"
excluded-patches = "'Custom branding' 'Enable debugging'"
arch = "arm64-v8a"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
